# Generated by Django 3.0.6 on 2020-06-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('time', models.IntegerField()),
                ('no_persons', models.IntegerField()),
            ],
        ),
    ]
