# Generated by Django 3.0.6 on 2020-06-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_reservationtable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtable',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
