# Generated by Django 3.0.6 on 2020-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200626_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeklyFeaturedFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
    ]
