# Generated by Django 3.0.6 on 2020-06-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsdatabase',
            name='displayContent',
            field=models.CharField(default='', max_length=450),
            preserve_default=False,
        ),
    ]
