# Generated by Django 3.0.6 on 2020-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogsdatabase_displaycontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsdatabase',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogsdatabase',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
